services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: sh -c "pnpm install && HOST=0.0.0.0 pnpm dev"
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./logs/app:/app/logs
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - HOST=0.0.0.0
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

  log-viewer:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    environment:
      - DOZZLE_BASE=/logs
      - DOZZLE_TAILSIZE=100
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: next-network
