/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9ziXN1Jkmxt
 */
import { Button } from "@/components/ui/button"

export function Compare() {
  return (
    <div className="grid items-center gap-4 w-full max-w-3xl mx-auto">
      <div className="relative">
        <img
          alt="Before Image"
          className="aspect-3/2 object-cover rounded-lg overflow-hidden"
          height={667}
          src="/placeholder.svg"
          width={1000}
        />
        <div className="absolute inset-0 flex items-center justify-center p-4">
          <div className="grid gap-2 text-center">
            <img
              alt="After Image"
              className="aspect-3/2 object-cover rounded-lg overflow-hidden"
              height={667}
              src="/placeholder.svg"
              width={1000}
            />
            <Button className="w-full max-w-xs mx-auto" variant="outline">
              Compare
            </Button>
          </div>
        </div>
      </div>
      <div className="grid gap-1 text-center">
        <p className="text-xs tracking-wide uppercase opacity-60">Kitchen Remodel</p>
        <p className="text-xs tracking-wide uppercase opacity-60">Location: Springfield, IL</p>
      </div>
    </div>
  )
}
