/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vy4PzC5K59Q
 */
import { Button } from "@/components/ui/button";
import Image from "next/legacy/image"; // Import the Image component from next/image

export function FoodTruckLandingSection() {
  return (
    <div className="grid w-full min-h-screen items-start gap-4 p-4 text-sm md:gap-8 md:p-10 lg:items-center lg:gap-10 xl:gap-16">
      <div className="flex flex-col gap-4 md:gap-2">
        <div className="text-center">
          <Image
            alt="Food Truck"
            className="mx-auto aspect-video overflow-hidden rounded-lg"
            src="/placeholder.svg"
            width={400} // Specify width
            height={200} // Specify height
            layout="intrinsic" // This prop is optional but can be used to maintain the aspect ratio without specifying device sizes
          />
        </div>
        <div className="mx-auto max-w-[700px] grid gap-4 lg:gap-6">
          <h1 className="text-3xl font-bold tracking-tight md:text-5xl">Acme Food Truck</h1>
          <div className="grid gap-2 md:gap-4">
            <p className="text-gray-500 dark:text-gray-400">The best street food in the city. 🌭🍔🍟</p>
            <div className="flex flex-wrap gap-2 items-center justify-center">
              <Button size="sm">Order Now</Button>
              <Button size="sm" variant="outline">
                View Menu
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
