/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/X1U03MbG694
 */


export function HoverGallery() {
  return (
    <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 max-w-5xl mx-auto">
      <div className="relative group rounded-lg overflow-hidden aspect-container">
        <img
          alt="Kitchen Renovation"
          className="object-cover w-full h-[calc(100% + 20px)] translate-y-10 group-hover:translate-y-0 transition-transform aspect-container"
          height={400}
          src="/placeholder.svg"
          width={600}
        />
        <div className="absolute inset-0 flex flex-col items-center justify-center p-4 gap-2 text-center bg-gray-900/50 transition-opacity opacity-0 group-hover:opacity-100 dark:bg-gray-50/50 dark:text-gray-900/50">
          <h3 className="text-sm font-semibold">Kitchen Renovation</h3>
          <p className="text-xs">Custom cabinets and modern appliances</p>
        </div>
      </div>
      <div className="relative group rounded-lg overflow-hidden aspect-container">
        <img
          alt="Bathroom Remodel"
          className="object-cover w-full h-[calc(100% + 20px)] translate-y-10 group-hover:translate-y-0 transition-transform aspect-container"
          height={400}
          src="/placeholder.svg"
          width={600}
        />
        <div className="absolute inset-0 flex flex-col items-center justify-center p-4 gap-2 text-center bg-gray-900/50 transition-opacity opacity-0 group-hover:opacity-100 dark:bg-gray-50/50 dark:text-gray-900/50">
          <h3 className="text-sm font-semibold">Bathroom Remodel</h3>
          <p className="text-xs">Spa-like shower and elegant fixtures</p>
        </div>
      </div>
      <div className="relative group rounded-lg overflow-hidden aspect-container">
        <img
          alt="Living Space Upgrade"
          className="object-cover w-full h-[calc(100% + 20px)] translate-y-10 group-hover:translate-y-0 transition-transform aspect-container"
          height={400}
          src="/placeholder.svg"
          width={600}
        />
        <div className="absolute inset-0 flex flex-col items-center justify-center p-4 gap-2 text-center bg-gray-900/50 transition-opacity opacity-0 group-hover:opacity-100 dark:bg-gray-50/50 dark:text-gray-900/50">
          <h3 className="text-sm font-semibold">Living Space Upgrade</h3>
          <p className="text-xs">Open concept and natural light</p>
        </div>
      </div>
      <div className="relative group rounded-lg overflow-hidden aspect-container">
        <img
          alt="Exterior Transformation"
          className="object-cover w-full h-[calc(100% + 20px)] translate-y-10 group-hover:translate-y-0 transition-transform aspect-container"
          height={400}
          src="/placeholder.svg"
          width={600}
        />
        <div className="absolute inset-0 flex flex-col items-center justify-center p-4 gap-2 text-center bg-gray-900/50 transition-opacity opacity-0 group-hover:opacity-100 dark:bg-gray-50/50 dark:text-gray-900/50">
          <h3 className="text-sm font-semibold">Exterior Transformation</h3>
          <p className="text-xs">Curb appeal and outdoor living</p>
        </div>
      </div>
    </div>
  )
}
