/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OqMEGLv2UCs
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function Pricing() {
  return (
    <div className="relative bg-gray-50 border-t border-gray-100 dark:bg-gray-950 dark:border-gray-850">
      <div className="container py-12 md:py-16">
        <div className="grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Choose your Plan</h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              {`Enjoy delicious meals for your team. Contact us to set up a personalized plan.`}
            </p>
          </div>
          <div className="grid max-w-sm gap-4 mx-auto sm:grid-cols-2 lg:max-w-none lg:grid-cols-3">
            <Card className="border-gray-200 shadow-sm dark:border-gray-800">
              <div className="grid gap-4 p-4">
                <CardHeader>
                  <CardTitle className="text-2xl font-semibold">🌿 Re-occurring Landscaping</CardTitle>
                  <CardDescription className="text-gray-500">
                    {`Elevate your outdoors with our continuous care, whether you need us biweekly, monthly, quartly, or otherwise`}
                  </CardDescription>
                </CardHeader>
                <CardContent className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xl font-semibold">Starting at</span>
                    <span className="text-xl font-semibold">$10/sqft</span>
                  </div>
                  <Button size="lg">Contact Sales</Button>
                </CardContent>
              </div>
            </Card>
            <Card className="border-gray-200 shadow-sm dark:border-gray-800">
              <div className="grid gap-4 p-4">
                <CardHeader>
                  <CardTitle className="text-2xl font-semibold">🏗️ Construction</CardTitle>
                  <CardDescription className="text-gray-500">
                    {`Transform ideas into iconic structures. Perfect for when only the extraordinary will do. Our team of artisans and master builders will transform your vision into a structural marvel, a backdrop worthy of the grandest occasions.`}
                  </CardDescription>
                </CardHeader>
                <CardContent className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xl font-semibold">Starting at</span>
                    <span className="text-xl font-semibold">$20/person</span>
                  </div>
                  <Button size="lg">Contact Sales</Button>
                </CardContent>
              </div>
            </Card>
            <Card className="border-gray-200 shadow-sm dark:border-gray-800">
              <div className="grid gap-4 p-4">
                <CardHeader>
                  <CardTitle className="text-2xl font-semibold">🏢 Concrete</CardTitle>
                  <CardDescription className="text-gray-500">
                    {`Goldson's Concrete services lay the foundation for your future. Experience a blend of resilience and precision, as we deliver concrete solutions that endure. Establish the strength of your project with our expertise.`}
                  </CardDescription>
                </CardHeader>
                <CardContent className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xl font-semibold">Starting at</span>
                    <span className="text-xl font-semibold">$15/person</span>
                  </div>
                  <Button size="lg">Contact Sales</Button>
                </CardContent>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
