/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UCWdSM5Oj2g
 */
import Link from "next/link";
import { Button } from "@/components/ui/common/button";
import { Input } from "@/components/ui/common/input";
import { Textarea } from "@/components/ui/common/textarea";
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/common/select";
import { AvatarImage, Avatar } from "@/components/ui/common/avatar";

export function AccountSettings() {
  return (
    <div className="max-w-4xl mx-auto my-6 p-4 bg-white rounded-lg shadow-md">
      <div className="flex">
        <aside className="w-64">
          <nav className="space-y-1">
            <Link className="block px-3 py-2 rounded-md bg-gray-200 text-black" href="#">
              Account
            </Link>
            <Link className="block px-3 py-2 rounded-md hover:bg-gray-100 text-gray-700" href="#">
              Appearance
            </Link>
            <Link className="block px-3 py-2 rounded-md hover:bg-gray-100 text-gray-700" href="#">
              Accessibility
            </Link>
            <Link className="block px-3 py-2 rounded-md hover:bg-gray-100 text-gray-700" href="#">
              Notifications
            </Link>
          </nav>
        </aside>
        <div className="flex-1 pl-8">
          <div className="flex justify-between">
            <h1 className="text-2xl font-semibold">Public profile</h1>
            <Button className="text-blue-600 border-blue-600" variant="outline">
              Edit
            </Button>
          </div>
          <div className="mt-4 grid grid-cols-3 gap-4">
            <div className="col-span-2">
              <div className="flex flex-col space-y-4">
                <Input defaultValue="ebowwa" placeholder="Name" />
                <Input defaultValue="ebowwa@example.com" placeholder="Public email" />
                <Textarea defaultValue="Self-taught, silo'd programmer, former solar guy. Interested in ML, AR, and everyday solutions. Feel the AGI!" placeholder="Bio" />
                <Select>
                  <SelectTrigger id="pronouns">
                    <SelectValue placeholder="Pronouns" />
                  </SelectTrigger>
                  <SelectContent position="popper">
                    <SelectItem value="he/him">He/Him</SelectItem>
                    <SelectItem value="she/her">She/Her</SelectItem>
                    <SelectItem value="they/them">They/Them</SelectItem>
                    <SelectItem value="don't specify">{/* Don't specify */}</SelectItem>
                  </SelectContent>
                </Select>
                <Input defaultValue="https://ebowwa.vercel.app/" placeholder="URL" />
                <Input defaultValue="The Simulation" placeholder="Company" />
                <Input defaultValue="the simulation" placeholder="Location" />
              </div>
            </div>
            <div className="flex flex-col items-center">
              <Avatar>
                <AvatarImage alt="Profile Picture" src="/placeholder.svg?height=128&width=128" />
              </Avatar>
              <Button className="mt-2 text-blue-600 border-blue-600" variant="outline">
                Change picture
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
