/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5OKhCf5QwS9
 */
import Link from "next/link"
import { Button } from "@/components/ui/common/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/common/card"
import { Input } from "@/components/ui/common/input"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import MapPinIcon from "@/components/icons/MapPinIcon"
import CalendarIcon from "@/components/icons/CalendarIcon"
import SearchIcon from "@/components/icons/SearchIcon"
import SettingsIcon from "@/components/icons/SettingsIcon"
import UsersIcon from "@/components/icons/UsersIcon"
import CreditCardIcon from "@/components/icons/CreditCardIcon"
import PackageIcon from "@/components/icons/PackageIcon"
import HomeIcon from "@/components/icons/HomeIcon"
import BellIcon from "@/components/icons/BellIcon"
import Package2Icon from "@/components/icons/Package2Icon"
import { useRouter } from 'next/navigation';





export function BrowseVendors() {
  const router = useRouter();

  return (
    <div className="grid min-h-screen w-full lg:grid-cols-[280px_1fr]">
      <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
        <div className="flex h-full max-h-screen flex-col gap-2">
          <div className="flex h-[60px] items-center border-b px-6">
            <Link className="flex items-center gap-2 font-semibold" href="#">
              <Package2Icon className="h-6 w-6" />
              <span className="">Edesia</span>
            </Link>
            <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
              <BellIcon className="h-4 w-4" />
              <span className="sr-only">Toggle notifications</span>
            </Button>
          </div>
          <div className="flex-1 overflow-auto py-2">
            <nav className="grid items-start px-4 text-sm font-medium">
              <Link
                className="flex items-center gap-3 rounded-lg bg-gray-100 px-3 py-2 text-gray-900  transition-all hover:text-gray-900 dark:bg-gray-800 dark:text-gray-50 dark:hover:text-gray-50"
                href="#"
              >
                <HomeIcon className="h-4 w-4" />
                Home
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <PackageIcon className="h-4 w-4" />
                Events
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <UsersIcon className="h-4 w-4" />
                Vendors
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <CreditCardIcon className="h-4 w-4" />
                Billing
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <SettingsIcon className="h-4 w-4" />
                Settings
              </Link>
            </nav>
          </div>
          <div className="mt-auto p-4">
            <Card>
              <CardHeader className="pb-4">
                <CardTitle>Upgrade to Pro</CardTitle>
                <CardDescription>Unlock all features and get unlimited access to our support team</CardDescription>
              </CardHeader>
              <CardContent>
                <Button className="w-full" size="sm">
                  Upgrade
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <header className="flex h-14 lg:h-[60px] items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
          <Link className="lg:hidden" href="#">
            <Package2Icon className="h-6 w-6" />
            <span className="sr-only">Home</span>
          </Link>
          <div className="flex-1">
            <form>
              <div className="relative">
                <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
                <Input
                  className="pl-8 md:w-2/3 lg:w-1/3 bg-white shadow-none appearance-none dark:bg-gray-950"
                  placeholder="Search events..."
                  type="search"
                />
              </div>
            </form>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800"
                size="icon"
                variant="ghost"
              >
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <div className="grid gap-4">
            <div className="flex items-center gap-4">
              <h1 className="font-semibold text-lg md:text-2xl">Home</h1>
              <Button className="ml-auto" size="sm" onClick={() => router.push("/getting-started")}>
                 Create event
              </Button>
            </div>
            <Card>
              <CardContent className="p-6">
                <div className="grid gap-4 md:grid-cols-2">
                  <div className="flex items-center gap-4">
                    <img
                      alt="Event image"
                      className="rounded-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "200/200",
                        objectFit: "cover",
                      }}
                      width="200"
                    />
                    <div className="grid gap-1.5">
                      <h2 className="font-semibold text-xl">Street Food Festival</h2>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        Hosted by
                        <span className="font-medium">Foodie Ventures</span>
                      </p>
                      <p className="text-sm">
                        <CalendarIcon className="w-4 h-4 mr-1 inline-block" />
                        September 20, 2022
                      </p>
                      <p className="text-sm">
                        <MapPinIcon className="w-4 h-4 mr-1 inline-block" />
                        Central Park, New York
                      </p>
                    </div>
                  </div>
                  <div className="grid gap-1.5">
                    <h2 className="font-semibold text-xl">Street Food Festival</h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Hosted by
                      <span className="font-medium">Foodie Ventures</span>
                    </p>
                    <p className="text-sm">
                      <CalendarIcon className="w-4 h-4 mr-1 inline-block" />
                      September 20, 2022
                    </p>
                    <p className="text-sm">
                      <MapPinIcon className="w-4 h-4 mr-1 inline-block" />
                      Central Park, New York
                    </p>
                    <div className="flex items-center gap-4">
                      <Button>View Vendors</Button>
                      <Button>Manage event commit</Button>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-6">
                <div className="grid gap-4 md:grid-cols-2">
                  <div className="flex items-center gap-4">
                    <img
                      alt="Event image"
                      className="rounded-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "200/200",
                        objectFit: "cover",
                      }}
                      width="200"
                    />
                    <div className="grid gap-1.5">
                      <h2 className="font-semibold text-xl">Street Food Festival</h2>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        Hosted by
                        <span className="font-medium">Foodie Ventures</span>
                      </p>
                      <p className="text-sm">
                        <CalendarIcon className="w-4 h-4 mr-1 inline-block" />
                        September 20, 2022
                      </p>
                      <p className="text-sm">
                        <MapPinIcon className="w-4 h-4 mr-1 inline-block" />
                        Central Park, New York
                      </p>
                    </div>
                  </div>
                  <div className="grid gap-1.5">
                    <h2 className="font-semibold text-xl">Street Food Festival</h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Hosted by
                      <span className="font-medium">Foodie Ventures</span>
                    </p>
                    <p className="text-sm">
                      <CalendarIcon className="w-4 h-4 mr-1 inline-block" />
                      September 20, 2022
                    </p>
                    <p className="text-sm">
                      <MapPinIcon className="w-4 h-4 mr-1 inline-block" />
                      Central Park, New York
                    </p>
                    <div className="flex items-center gap-4">
                      <Button>View attendees</Button>
                      <Button>Manage event</Button>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-6">
                <div className="grid gap-4 md:grid-cols-2">
                  <div className="flex items-center gap-4">
                    <img
                      alt="Event image"
                      className="rounded-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "200/200",
                        objectFit: "cover",
                      }}
                      width="200"
                    />
                    <div className="grid gap-1.5">
                      <h2 className="font-semibold text-xl">Street Food Festival</h2>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        Hosted by
                        <span className="font-medium">Foodie Ventures</span>
                      </p>
                      <p className="text-sm">
                        <CalendarIcon className="w-4 h-4 mr-1 inline-block" />
                        September 20, 2022
                      </p>
                      <p className="text-sm">
                        <MapPinIcon className="w-4 h-4 mr-1 inline-block" />
                        Central Park, New York
                      </p>
                    </div>
                  </div>
                  <div className="grid gap-1.5">
                    <h2 className="font-semibold text-xl">Street Food Festival</h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Hosted by
                      <span className="font-medium">Foodie Ventures</span>
                    </p>
                    <p className="text-sm">
                      <CalendarIcon className="w-4 h-4 mr-1 inline-block" />
                      September 20, 2022
                    </p>
                    <p className="text-sm">
                      <MapPinIcon className="w-4 h-4 mr-1 inline-block" />
                      Central Park, New York
                    </p>
                    <div className="flex items-center gap-4">
                      <Button>View attendees</Button>
                      <Button>Manage event</Button>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </div>
  )
}

