/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xsqNsFkEgKP
 */
import Link from "next/link"
import { Input } from "@/components/ui/common/input"
import { Button } from "@/components/ui/common/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { CardTitle, CardDescription, CardContent, Card } from "@/components/ui/common/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/common/table"

import SearchIcon from "@/components/icons/SearchIcon"
import Package2Icon from "@/components/icons/Package2Icon"
import LineChartIcon from "@/components/icons/LineChartIcon"
import UsersIcon from "@/components/icons/UsersIcon"
import PackageIcon from "@/components/icons/PackageIcon"
import ShoppingCartIcon from "@/components/icons/ShopingCartIcon"
import HomeIcon from "@/components/icons/HomeIcon"


export function VendorDashboardIntro() {
  return (
    <div className="grid min-h-screen w-full overflow-hidden lg:grid-cols-[280px_1fr]">
      <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
        <div className="flex flex-col gap-2">
          <div className="flex h-[60px] items-center px-6">
            <Link className="flex items-center gap-2 font-semibold" href="#">
              <Package2Icon className="h-6 w-6" />
              <span className="">Acme Inc</span>
            </Link>
          </div>
          <div className="flex-1">
            <nav className="grid items-start px-4 text-sm font-medium">
              <Link
                className="flex items-center gap-3 rounded-lg bg-gray-100 px-3 py-2 text-gray-900  transition-all hover:text-gray-900 dark:bg-gray-800 dark:text-gray-50 dark:hover:text-gray-50"
                href="#"
              >
                <HomeIcon className="h-4 w-4" />
                Home
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <ShoppingCartIcon className="h-4 w-4" />
                Orders
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <PackageIcon className="h-4 w-4" />
                Products
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <UsersIcon className="h-4 w-4" />
                Customers
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <LineChartIcon className="h-4 w-4" />
                Analytics
              </Link>
            </nav>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <header className="flex h-14 lg:h-[60px] items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
          <Link className="lg:hidden" href="#">
            <Package2Icon className="h-6 w-6" />
            <span className="sr-only">Home</span>
          </Link>
          <div className="w-full flex-1">
            <h1 className="font-semibold text-lg">Orders</h1>
          </div>
          <form className="w-full max-w-[300px] flex-1">
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input className="pl-8 bg-gray-100/40 dark:bg-gray-800/40" placeholder="Search orders..." type="search" />
            </div>
          </form>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800"
                size="icon"
                variant="ghost"
              >
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <div className="grid gap-4 md:grid-cols-[2_1]">
            <Card>
              <CardContent className="flex flex-col md:flex-row gap-4">
                <div className="flex flex-col gap-1">
                  <CardTitle>Orders</CardTitle>
                  <CardDescription>View and manage your recent orders</CardDescription>
                </div>
                <div className="flex flex-col gap-1">
                  <CardTitle>Revenue</CardTitle>
                  <CardDescription>Track your sales and revenue over time</CardDescription>
                </div>
                <div className="flex flex-col gap-1">
                  <CardTitle>Customers</CardTitle>
                  <CardDescription>Manage your customer database</CardDescription>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex flex-col gap-4">
                <div className="flex flex-col gap-1">
                  <CardTitle>Total Orders</CardTitle>
                  <CardDescription className="text-4xl font-bold">320</CardDescription>
                </div>
                <div className="flex flex-col gap-1">
                  <CardTitle>Total Revenue</CardTitle>
                  <CardDescription className="text-4xl font-bold">$12,450.00</CardDescription>
                </div>
                <div className="flex flex-col gap-1">
                  <CardTitle>Average Order Value</CardTitle>
                  <CardDescription className="text-4xl font-bold">$38.91</CardDescription>
                </div>
              </CardContent>
            </Card>
          </div>
          <div className="border shadow-sm rounded-lg">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[100px]">Order</TableHead>
                  <TableHead className="min-w-[150px]">Customer</TableHead>
                  <TableHead className="hidden md:table-cell">Channel</TableHead>
                  <TableHead className="hidden md:table-cell">Date</TableHead>
                  <TableHead className="text-right">Total</TableHead>
                  <TableHead className="hidden sm:table-cell">Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">#3210</TableCell>
                  <TableCell>Olivia Martin</TableCell>
                  <TableCell className="hidden md:table-cell">Online Store</TableCell>
                  <TableCell className="hidden md:table-cell">February 20, 2022</TableCell>
                  <TableCell className="text-right">$42.25</TableCell>
                  <TableCell className="hidden sm:table-cell">Shipped</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">#3209</TableCell>
                  <TableCell>Ava Johnson</TableCell>
                  <TableCell className="hidden md:table-cell">Shop</TableCell>
                  <TableCell className="hidden md:table-cell">January 5, 2022</TableCell>
                  <TableCell className="text-right">$74.99</TableCell>
                  <TableCell className="hidden sm:table-cell">Paid</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">#3204</TableCell>
                  <TableCell>Michael Johnson</TableCell>
                  <TableCell className="hidden md:table-cell">Shop</TableCell>
                  <TableCell className="hidden md:table-cell">August 3, 2021</TableCell>
                  <TableCell className="text-right">$64.75</TableCell>
                  <TableCell className="hidden sm:table-cell">Unfulfilled</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">#3203</TableCell>
                  <TableCell>Lisa Anderson</TableCell>
                  <TableCell className="hidden md:table-cell">Online Store</TableCell>
                  <TableCell className="hidden md:table-cell">July 15, 2021</TableCell>
                  <TableCell className="text-right">$34.50</TableCell>
                  <TableCell className="hidden sm:table-cell">Shipped</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">#3202</TableCell>
                  <TableCell>Samantha Green</TableCell>
                  <TableCell className="hidden md:table-cell">Shop</TableCell>
                  <TableCell className="hidden md:table-cell">June 5, 2021</TableCell>
                  <TableCell className="text-right">$89.99</TableCell>
                  <TableCell className="hidden sm:table-cell">Paid</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </main>
      </div>
    </div>
  )
}

