/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yL8C6ncNFCL
 */
import { ProductCard } from "./ui/ProductCard";
import Header from "@/components/layout/Header"; 
import { Footer } from "@/components/layout/Footer";
import { SanrioDisclaimerCard } from '@/components/SanrioDisclaimerCard';
import StripeBuyButton from '@/components/StripeListing'

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <Header /> {/* Use the Header component */}
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container flex flex-col items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">My Melody Merch</h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                The cutest collectibles for all My Melody fans. Limited edition. Shop now.
              </p>
            </div>
            <SanrioDisclaimerCard />
          </div>
          <StripeBuyButton />
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">New Arrivals</h2>
            </div>
            <div className="mx-auto w-full max-w-[900px] grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              <ProductCard imageUrl="/placeholder.svg" title="My Melody Plush" price="$19.99" />
              <ProductCard imageUrl="/placeholder.svg" title="Kuromi Tee" price="$29.99" />
              <ProductCard imageUrl="/placeholder.svg" title="Cinnamoroll Backpack" price="$39.99" />
            </div>
          </div>
        </section>
      </main>
      <Footer /> {/* Use the extracted Footer component */}
    </div>
  );
}
