/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ck6IqhF4Ltx
 */

import React from 'react';
import AlertCircleIcon from '@/components/icons/AlertCircleIcon'; // Adjust the import path as necessary

export function SanrioDisclaimerCard() {
  return (
    <div key="1" className="border border-gray-200 rounded-lg p-6 flex items-center gap-4 mx-auto max-w-xl">
      <AlertCircleIcon className="w-20 h-20 text-yellow-500" />
      <div className="text-sm leading-none">
        <p className="font-semibold">We are not Sanrio</p>
        <p className="text-sm text-gray-500">
          All products are sourced and sold through The First Sale Doctrine, emphasizing our independence from Sanrio.
          By incorporating this disclaimer, we aim to manage customer expectations and mitigate the risk of trademark
          infringement claims.
        </p>
      </div>
    </div>
  );
}
